### ISSUE TITLE
difficulty of setting up VST's or other C libs as algorithms?

### ISSUE THREAD

**Issue by bradwbradw** [expertsleepersltd/disting#2]
Just a question about how feasible this would be, or any general direction / guidance for how this could be achieved?  

I would think that the Disting would have pretty good D/A conversion, and that would be the only reason for doing this instead of using a computer.

1) I'd like to set up https://github.com/munt/munt as an algorithm that takes midi data and outputs audio

2) How hard would it be to set up any C based VST that has 2 in's and 2 out's (mapping X/Y and A/B)

**Comment by expertsleepers** [comment]
It would be pretty simple to port a VST over. Just plug the VST's render method in where the algorithm core is: 
https://github.com/expertsleepersltd/disting/blob/c5fffb60e9213e153a2e8dbd921f9981e1f0697c/hello_disting_mk4/algorithms.c#L37

Remember there's no hardware floating point though.

**Comment by bradwbradw** [comment]
Cool.  Could you elaborate a little more on the comment about no floating point?  Does that mean only integers?

**Comment by expertsleepers** [comment]
Yes.
